### ISSUE TITLE
When will the code be published?

### ISSUE THREAD

**Issue by dipjyoti92** [nii-yamagishilab/multi-speaker-tacotron#1]
Dear authors,

The paper is very interesting. Any news on when the code will be published?

**Comment by Mugaduka** [comment]
Thanks for code! This link from Dependencies is not valid: https://github.com/nii-yamagishilab/multi-speaker-tacotron-internal.git. How can I get "multi-speaker-tacotron-internal" project? Is it the same as https://github.com/nii-yamagishilab/multi-speaker-tacotron ?

**Comment by ecooper7** [comment]
yes, please use multi-speaker-tacotron.git instead.  thanks for catching that, I've updated the instructions.
