### ISSUE TITLE
problem downloading data from Dropbox

### ISSUE THREAD

**Issue by marzieh-razavi** [nii-yamagishilab/multi-speaker-tacotron#3]
Hello, I have tried downloading the data from the dropbox link you provided (https://www.dropbox.com/sh/rq4lebus0n8tmso/AACldbmKDPRN9YiXrRROjtTSa?dl=0). But unfortunately, I am getting the "Folder has too many files to download" error. I have also tried using "wget https://www.dropbox.com/sh/rq4lebus0n8tmso/AACldbmKDPRN9YiXrRROjtTSa?dl=1" command but I was still not able to download the data.  I would be really grateful if you could provide a link to the dropbox which can be downloaded through wget command, or provide a zip version of the data folder. Thank you very much for the help.

**Comment by ecooper7** [comment]
Hi, thanks for bringing this to my attention.  I have replaced the folders with .zip files -- please let me know if you still have issues downloading the data.

**Comment by marzieh-razavi** [comment]
Thank you very much for providing the zip file. I was able to download the data.

**Comment by ecooper7** [comment]
great, thanks for letting me know.
